#!/bin/bash
echo "Content-type: text/html"
echo "Server: IceCliffs-PowerfulShell-Blog"
echo ""
echo "<!--"
echo " ----------------------------------------------"
echo "<   Moo~ Everybody say Moo~ Moo~ Moo~ Moo~ -   >"
echo " ----------------------------------------------"
echo "        \\   ^__^"
echo "         \\  (oo)\_______"
echo "            (__)\       )\\/\\"
echo "                ||----w |"
echo "                ||     ||   "
echo "-->"
echo -n "<html>"
echo -n "<head><title>Po7mn1's Blog</title><style>a:visited{color: white;}</style><link rel='stylesheet' href='https://bfs.iloli.moe/rce_status/style.css'><link rel='stylesheet' href='https://bfs.iloli.moe/rce_status/emoji.css'></head>"
echo -n "<body>"
echo -n ""